# Generated by Django 5.2.7 on 2025-12-16 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Consulta de Productos'), ('CONVERSION', 'Conversión de Moneda'), ('BUSQUEDA', 'Búsqueda')], max_length=20)),
                ('api_nombre', models.CharField(max_length=100)),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitosa', models.BooleanField(default=True)),
                ('detalles', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consulta de API',
                'verbose_name_plural': 'Consultas de APIs',
                'db_table': 'api_consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(help_text='ID del producto en la API externa', unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_cop', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('sincronizado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto de API',
                'verbose_name_plural': 'Productos de API',
                'db_table': 'api_productos',
                'ordering': ['-sincronizado_en'],
            },
        ),
    ]
