# Generated by Django 5.2.7 on 2025-11-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='creado',
            new_name='creado_en',
        ),
    ]
